apiVersion: v1
kind: ServiceAccount
metadata:
  name: vectorflow-prometheus
  namespace: vectorflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vectorflow-prometheus-discovery
  namespace: vectorflow
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vectorflow-prometheus-discovery
  namespace: vectorflow
subjects:
  - kind: ServiceAccount
    name: vectorflow-prometheus
    namespace: vectorflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vectorflow-prometheus-discovery
