apiVersion: v1
kind: Secret
metadata:
  name: vectorflow-db-secret
  namespace: vectorflow
type: Opaque
stringData:
  POSTGRES_USER: flow_admin
  POSTGRES_PASSWORD: flow_password
  POSTGRES_DB: flow_db
